// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/auth/login.ts";
import * as $3 from "./routes/api/auth/logout.ts";
import * as $4 from "./routes/api/customers/[id].ts";
import * as $5 from "./routes/api/orders/[id].ts";
import * as $6 from "./routes/api/products/[id].ts";
import * as $7 from "./routes/customers/[id].tsx";
import * as $8 from "./routes/customers/list.tsx";
import * as $9 from "./routes/customers/new.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/login.tsx";
import * as $12 from "./routes/orders/list.tsx";
import * as $13 from "./routes/orders/new/[id].tsx";
import * as $14 from "./routes/products/[id].tsx";
import * as $15 from "./routes/products/list.tsx";
import * as $16 from "./routes/products/new.tsx";
import * as $$0 from "./islands/auth/Login.tsx";
import * as $$1 from "./islands/customers/Customer.tsx";
import * as $$2 from "./islands/customers/EditCustomer.tsx";
import * as $$3 from "./islands/customers/NewCustomer.tsx";
import * as $$4 from "./islands/orders/AmountProduct.tsx";
import * as $$5 from "./islands/orders/NewOrder.tsx";
import * as $$6 from "./islands/orders/Order.tsx";
import * as $$7 from "./islands/orders/SearchProduct.tsx";
import * as $$8 from "./islands/products/EditProduct.tsx";
import * as $$9 from "./islands/products/NewProduct.tsx";
import * as $$10 from "./islands/products/Product.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/auth/login.ts": $2,
    "./routes/api/auth/logout.ts": $3,
    "./routes/api/customers/[id].ts": $4,
    "./routes/api/orders/[id].ts": $5,
    "./routes/api/products/[id].ts": $6,
    "./routes/customers/[id].tsx": $7,
    "./routes/customers/list.tsx": $8,
    "./routes/customers/new.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/login.tsx": $11,
    "./routes/orders/list.tsx": $12,
    "./routes/orders/new/[id].tsx": $13,
    "./routes/products/[id].tsx": $14,
    "./routes/products/list.tsx": $15,
    "./routes/products/new.tsx": $16,
  },
  islands: {
    "./islands/auth/Login.tsx": $$0,
    "./islands/customers/Customer.tsx": $$1,
    "./islands/customers/EditCustomer.tsx": $$2,
    "./islands/customers/NewCustomer.tsx": $$3,
    "./islands/orders/AmountProduct.tsx": $$4,
    "./islands/orders/NewOrder.tsx": $$5,
    "./islands/orders/Order.tsx": $$6,
    "./islands/orders/SearchProduct.tsx": $$7,
    "./islands/products/EditProduct.tsx": $$8,
    "./islands/products/NewProduct.tsx": $$9,
    "./islands/products/Product.tsx": $$10,
  },
  baseUrl: import.meta.url,
};

export default manifest;
