// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/customers/edit/[id].tsx";
import * as $3 from "./routes/customers/list.tsx";
import * as $4 from "./routes/customers/new.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/orders/edit/[id].tsx";
import * as $7 from "./routes/orders/list.tsx";
import * as $8 from "./routes/orders/new/[id].tsx";
import * as $9 from "./routes/products/edit/[id].tsx";
import * as $10 from "./routes/products/list.tsx";
import * as $11 from "./routes/products/new.tsx";
import * as $$0 from "./islands/customers/Customer.tsx";
import * as $$1 from "./islands/customers/EditCustomer.tsx";
import * as $$2 from "./islands/customers/NewCustomer.tsx";
import * as $$3 from "./islands/orders/EditOrder.tsx";
import * as $$4 from "./islands/orders/NewOrder.tsx";
import * as $$5 from "./islands/orders/Order.tsx";
import * as $$6 from "./islands/products/EditProduct.tsx";
import * as $$7 from "./islands/products/NewProduct.tsx";
import * as $$8 from "./islands/products/Product.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/customers/edit/[id].tsx": $2,
    "./routes/customers/list.tsx": $3,
    "./routes/customers/new.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/orders/edit/[id].tsx": $6,
    "./routes/orders/list.tsx": $7,
    "./routes/orders/new/[id].tsx": $8,
    "./routes/products/edit/[id].tsx": $9,
    "./routes/products/list.tsx": $10,
    "./routes/products/new.tsx": $11,
  },
  islands: {
    "./islands/customers/Customer.tsx": $$0,
    "./islands/customers/EditCustomer.tsx": $$1,
    "./islands/customers/NewCustomer.tsx": $$2,
    "./islands/orders/EditOrder.tsx": $$3,
    "./islands/orders/NewOrder.tsx": $$4,
    "./islands/orders/Order.tsx": $$5,
    "./islands/products/EditProduct.tsx": $$6,
    "./islands/products/NewProduct.tsx": $$7,
    "./islands/products/Product.tsx": $$8,
  },
  baseUrl: import.meta.url,
};

export default manifest;
